name:                scrapti
version:             0.1.0
github:              "ejconlon/scrapti"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/scrapti#readme>

dependencies:
- base >= 4.12 && < 5
- bytestring >= 0.10 && < 0.11
- dahdit >= 0.1 && < 0.2
- data-default >= 0.7 && < 0.8
- digest >= 0.0.1 && < 0.0.2
- directory
- filepath
- regex-tdfa
- mtl >= 2.2 && < 2.3
- transformers >= 0.5 && < 0.6
- containers >= 0.6 && < 0.7
- primitive >= 0.7 && < 0.8
- text >= 1.2 && < 1.3

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

# executables:
#   scrapti-exe:
#     main:                Main.hs
#     source-dirs:         exe
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - scrapti

tests:
  scrapti-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrapti
    - tasty
    - tasty-hunit
