name:                scrapti
version:             0.1.0
github:              "ejconlon/scrapti"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/scrapti#readme>

dependencies:
- base >= 4.12 && < 5
- bytestring >= 0.10 && < 0.12
- containers >= 0.6 && < 0.7
- dahdit >= 0.5 && < 0.6
- data-default >= 0.7 && < 0.8
- data-sword >= 0.2 && < 0.3
- digest >= 0.0.1 && < 0.0.3
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && < 1.5
- mtl >= 2.2 && < 2.4
- primitive >= 0.7 && < 0.9
- regex-tdfa >= 1.3 && < 1.4
- text >= 1.2 && < 2.1
- transformers >= 0.5 && < 0.7
- microlens >= 0.4 && < 0.5
- prettyprinter >= 1.7 && < 1.8
- aeson >= 2.0 && < 2.2
- aeson-via >= 0.2 && < 0.3
- aeson-pretty >= 0.8 && < 0.9
- optparse-applicative >= 0.16 && < 0.19
- aeson-casing >= 0.2 && < 0.3
# Used as build plugin
- ghc-typelits-knownnat >= 0.7 && < 0.8

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

executables:
  scrapti-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrapti

tests:
  scrapti-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrapti
    - tasty >= 1.4 && < 1.5
    - tasty-hunit >= 0.10 && < 0.11
    - temporary >= 1.3 && < 1.4
    - pretty-simple
    - daytripper
