resolver: lts-20.22

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- aeson-via-0.2.1
# TODO Use Hackage version when released
# - dahdit-0.4.0
- git: git@github.com:ejconlon/dahdit.git
  commit: bf4c9bdbc3cf6eedf3d946704a6df3c027e5c888
- data-sword-0.2.0.3
- falsify-0.1.1
# TODO Use Hackage version when released
- git: git@github.com:ejconlon/dahdit-test.git
  commit: 569459c0e076546367edb7c3bed4c7a2b25218f3
