resolver: lts-20.17

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- aeson-via-0.2.1
# TODO use dahdit from hackage when released
# - dahdit-0.2.0
- git: git@github.com:ejconlon/dahdit.git
  commit: f517f40fddcd02bec7f1306eb33bfcb66bfc3f1e
- data-sword-0.2.0.3
