resolver: lts-19.22

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- aeson-via-0.2.0
- git: git@github.com:ejconlon/dahdit.git
  commit: a3939939f36a6cc2cbd4899cfedb29faebe0039d
- git: git@github.com:ejconlon/data-sword.git
  commit: 4a3efca54b337820446c7682bf3623d607f0365f
