resolver: lts-23.6

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- aeson-via-0.2.2
- dahdit-0.7.0
- data-sword-0.2.0.3
- daytripper-1.0.0
- prop-unit-1.0.1

allow-newer: true
allow-newer-deps: ['aeson-via']
