resolver: lts-19.19

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- git: git@github.com:ejconlon/dahdit.git
  commit: c592314d5a646d1af9c258368f5d1133587860bc
- git: git@github.com:ejconlon/data-sword.git
  commit: 4a3efca54b337820446c7682bf3623d607f0365f
